repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0    # Use the ref you want to point at
  hooks:
  - id: trailing-whitespace
  - id: check-toml
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.12.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']
