# The URL the site will be built for
base_url = "https://manifoldfr.github.io"

theme = "terminimal"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here

accent_color = "orange"

favicon = "/favicon-32x32.png"
favicon_mimetype = "image/png"

logo_text = "manifoldfr"

menu_items = [
    # each of these is optional, name and url are required
    # $BASE_URL is going to be substituted by base_url from configuration
    {name = "posts", url = "$BASE_URL/posts"},

    # {name = "about", url = "$BASE_URL"},

    # set newtab to true to make the link open in new tab
    {name = "github", url = "https://github.com/ManifoldFR"},
    {name = "google scholar", url = "https://scholar.google.com/citations?user=aVgy-0gAAAAJ&hl=en"}
]

page_titles = "Combined"
