title = "ManifoldFR"
# The URL the site will be built for
base_url = "https://manifoldfr.github.io"

theme = "terminus"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

taxonomies = [
    { name = "tags", feed = true },
]

[markdown.highlighting]
style = "inline"
theme = "monokai"

[extra]
layout = "center"
katex = true
show_default_author = false

color_scheme = "catppuccin-latte"

favicon = "favicon-32x32.png"

main_menu = [
    { name = "blog", url = "blog", trailing_slash = true },
    { name = "publications", url = "publications", trailing_slash = true },
    { name = "github", url = "https://github.com/ManifoldFR", new_tab = true },
    { name = "google scholar", url = "https://scholar.google.com/citations?user=aVgy-0gAAAAJ&hl=en", new_tab = true },
]
